### ISSUE TITLE
[SETTING] Project SetUp

### ISSUE THREAD

**Issue by lhs8701** [ORGO-Official/orgo-android#1]
## 💡 Description
Before Starting the Project, Set Basic settings.

## ✅ To-do
- [x] Set dependencies and Libraries
- [x] Set gitignore
- [x] Set multi-module basic architecture
- [x] Set Version Catalog (libs.versions.toml)
- [x] Set buildSrc for manage Configuration
- [x] Make Github Issue,PR templates
