### ISSUE TITLE
[FEAT] ClimbComplete

### ISSUE THREAD

**Issue by wooongyee** [ORGO-Official/orgo-android#23]
## 💡 Description
MapBottomSheet에서 등산 완료 버튼을 눌렀을 경우 이동하게 되는 등산 완료 결과를 보여주는 기능

<br/>

## ✅ To-do
- [x] 등산한 산에 대한 MountainDetail을 보여주는 Box 컴포넌트 구현
- [x] 갤러리에 저장하거나 공유할 수 있도록 하는 옵션을 보여주는 OptionBox 컴포넌트 구현
- [x] 갤러리에 저장 기능
- [x] 갤러리로부터 사진 가져오기 기능
- [x] 사진 촬영해서 사진 가져오기 기능
- [ ] 인스타그램으로 공유 기능
- [ ] 카카오톡으로 공유 기능

<br/>

## 🗨️ ETC

<br/>
