### ISSUE TITLE
[UI] Splash Screen

### ISSUE THREAD

**Issue by ys05059** [ORGO-Official/orgo-android#3]
## 💡 Description
The Development of Splash Screen

## ✅ To-do
- [x] Separating DesignSystem Module
- [x] Add LibraryComposeConventionPlugin
- [x] Implementation of Splash Screen
- [ ] Change or Resize Logo Icon

## 🗨️ ETC
**Development Diary in Notion (Korean)**
https://orgo-offical.notion.site/UI-Splash-Screen-2127ca31a78c441295ace8634df58b14?pvs=4
