### ISSUE TITLE
[Improve] Room을 활용하여 로컬 DB를 SST로 설정

### ISSUE THREAD

**Issue by wooongyee** [ORGO-Official/orgo-android#37]
## 💡 Description
현재 RemoteDataSource를 통해 서버로부터 데이터를 받아오고 있음. 
Room을 활용하여 로컬 DB에 데이터를 저장해둠으로 Offline 상태 대응.
네트워크의 데이터와 충돌을 피하기 위해 동기화하는 로직 처리.

<br/>

## ✅ To-do
- [ ] Model 설계
- [ ] DAO 작성
- [ ] Room 초기화 및 설정
- [ ] 각 데이터별 LocalDataSource 생성 및 관련 로직 처리
- [ ]  각 데이터별 RemoteDataSource와의 동기화 처리

<br/>

## 🗨️ ETC
- 스크린샷, 링크, 관련자료 등

<br/>
